FROM node:18 AS build-env

# Create app directory
WORKDIR /app

ENV TZ=Europe/Vienna
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# Install app dependencies
# You can set this variable to your desired version (e.g. v0.6.2)
ENV VERSION=main
RUN git clone --depth 1 --branch ${VERSION} https://github.com/MILA-Wien/collectivo-ux .

# Copy extensions into the root of the collectivo app
COPY ./extensions /app/src/extensions
COPY ./collectivo.json /app/src/collectivo.json
COPY ./favicon.ico /app/public/favicon.ico

RUN  yarn install --frozen-lockfile
