name: Collectivo-mila

# Controls when the workflow will run
on:
  workflow_call:
  push:
    tags-ignore:
      - "**"
  pull_request:
jobs:
  test-docker:
    name: Test docker environment
    runs-on: ubuntu-20.04
    steps:
      - name: Check Credentials
        run: |
          echo ${{ secrets.DOCKERHUB_USER }}
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build containers 
        run: |
          cp .env.example .env
          docker-compose up -d collectivo-db
          docker-compose build keycloak
          docker-compose up -d keycloak
          docker-compose build collectivo-ux
          docker-compose up -d collectivo-ux
          docker-compose build collectivo
      - name: Prepare for tests
        run: |
          docker-compose run --rm collectivo sh -c "python manage.py migrate"
  
      - name: Test
        run: |
          docker-compose run --rm collectivo sh -c "python manage.py test && flake8"
